version: '3'
services: 
    app:
        build: .
        image: app
        command: npm start
        ports:
            - 4200:4200
        environment: 
            PORT: 4200
        volumes: 
            - ./:/src/
            - nodemodules:/src/node_modules
volumes: 
    nodemodules: {}